### ISSUE TITLE
ConnectionOwner.scala:179: type mismatch

### ISSUE THREAD

**Issue by ghost** [sstone/amqp-client#19]
amqp-client-scala2.10/src/main/scala/com/github/sstone/amqp/ConnectionOwner.scala:179: type mismatch;
[error]  found   : Unit
[error]  required: ConnectionOwner.this.State
[error](which expands to)  akka.actor.FSM.State[com.github.sstone.amqp.ConnectionOwner.State,com.github.sstone.amqp.ConnectionOwner.Data]
[error]           setTimer("reconnect", 'connect, reconnectionDelay, true)
[error]                   ^
[error] one error found
[error](compile:compile) Compilation failed

**Comment by sstone** [comment]
Hi Prathvi,
Can you please specify which branch you are trying to compile ? How (sbt, maven) ?
I can compile all branches with maven (and so can Travis).
Also, when you open a new issue it's better to use a "real" short sentence ("branch xxx does not compile with sbt" for example) and a description.
I suspect that you tried to update akka from 2.1.4 to 2.2.0 on branch scala2.10. It does not work, there is already an issue for this, and a fix in branch wip-messages (which works with both 2.1.4 and 2.2.0)
Thanks
